[package]
name = "relayterm-application"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
relayterm-domain = { path = "../relayterm-domain", version = "0.1.0" }

[dev-dependencies]
serde_json.workspace = true
